let CATALOG = [
  {
    name: "Babki",
    img: "./Public/Carts/1.webp",
    price: "400",
    filter: "new",
    text: "Молодежная жидкоть Babki деалает странные ,но крутые вкусы,как вкус домашней медовухи.",
    low: "20мг",
    hard: "—",
  },
  {
    name: "Boshki CS",
    img: "./Public/Carts/boshki-cs.webp",
    price: "400",
    text: "Не часто встретишь жидкоть со вкусом хвойной клубничной колы,а она уже тут.",
    low: "20мг",
    hard: "—",
  },
  {
    name: "Boshki Fresh",
    img: "./Public/Carts/boshkisoch.webp",
    price: "400",
    text: "С Boshki сочные ты почувствуешь лето. Вкус: хвойный сок из яблок со апельсином.",
    low: "20мг",
    hard: "—",
  },
  {
    name: "Husky Choko",
    img: "./Public/Carts/chokoloco.webp",
    price: "450",
    filter: "rich",
    text: "Husky это то ,что не стареет. Вкус: шоколад с мятой.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "Jamgo Cherniy",
    img: "./Public/Carts/jamgocherniy.webp",
    price: "400",
    filter: "middle",
    text: "Jamgo - поражает своей вкуснейшей натурой. Вкус: йогурт с черничным джемом.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "Jamgo Ultramarin",
    img: "./Public/Carts/JumgoUltramarin.webp",
    price: "400",
    filter: "middle",
    text: "Jamgo - поражает своей вкуснейшей натурой. Вкус: йогурт с малиновым джемом и розами.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "MOPS",
    img: "./Public/Carts/MORS.webp",
    price: "400",
    filter: "middle",
    text: "Всегда популярная линейка жидкостей MOPC. Вкус:жимолость и облепиха",
    low: "20мг",
    hard: "—",
  },
  {
    name: "Podonki Wood",
    img: "./Public/Carts/PodonkiWood.webp",
    price: "450",
    filter: "rich",
    text: "Проверенные временем терпкие Podonki. Вкус: Лесные ягоды со льдом.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "SK Algaritnm",
    img: "./Public/Carts/SkAlg.webp",
    price: "400",
    filter: "new",
    text: "Новинка от SmokeKitchen. Вкус: Цитрус барбарис.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "SK Paradox",
    img: "./Public/Carts/SkGreip.webp",
    price: "400",
    filter: "new",
    text: "Новинка от SmokeKitchen. Вкус: Грейпфрукт с лесными ягодами.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "SK Duality",
    img: "./Public/Carts/SkQivi.webp",
    price: "400",
    filter: "new",
    text: "Новинка от SmokeKitchen. Вкус: Клубника с киви.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "SK Hybrid",
    img: "./Public/Carts/SkTrop.webp",
    price: "400",
    filter: "new",
    text: "Новинка от SmokeKitchen. Вкус: Тропический йогурт.",
    low: "—",
    hard: "40мг",
  },
  {
    name: "Ultra Hvoi",
    img: "./Public/Carts/UltraHV.webp",
    price: "350",
    filter: "middle",
    text: "Новая линейка жидкостей Ultra. Яркий вкус свежей далневосточной хвои. ",
    low: "—",
    hard: "40мг",
  },
  {
    name: "Ultra Guava",
    img: "./Public/Carts/UltraTea-1.webp",
    price: "350",
    filter: "middle",
    text: "Новая линейка жидкостей Ultra. Яркий вкус женьшеня,зеленого чая и сочной гуавы.",
    low: "—",
    hard: "40мг",
  },
];
